export const allCars = [
  {
    id: 1,
    constructeur: 'Audi',
    modèle: 'A3',
    année: 2003,
    consommation: '4,8 L/100 km',
    transmission: 'Automatique',
    carburant: 'Essence',
    prix: 49,
    image: '/assets/images/audi/a3.webp',
  },
  {
    id: 2,
    constructeur: 'Audi',
    modèle: 'A4',
    année: 2005,
    consommation: '5,2 L/100 km',
    transmission: 'Manuelle',
    carburant: 'Diesel',
    prix: 49,
    image: '/assets/images/audi/a4.webp',
  },
  {
    id: 3,
    constructeur: 'Audi',
    modèle: 'A6',
    année: 2007,
    consommation: '5,5 L/100 km',
    transmission: 'Automatique',
    carburant: 'Essence',
    prix: 49,
    image: '/assets/images/audi/a6.webp',
  },
  {
    id: 4,
    constructeur: 'Audi',
    modèle: 'Q3',
    année: 2009,
    consommation: '5,8 L/100 km',
    transmission: 'Manuelle',
    carburant: 'Diesel',
    prix: 79,
    image: '/assets/images/audi/q3.webp',
  },
  {
    id: 5,
    constructeur: 'Audi',
    modèle: 'Q5',
    année: 2011,
    consommation: '6,2 L/100 km',
    transmission: 'Automatique',
    carburant: 'Essence',
    prix: 79,
    image: '/assets/images/audi/q5.webp',
  },
  {
    id: 6,
    constructeur: 'Audi',
    modèle: 'Q7',
    année: 2013,
    consommation: '6,5 L/100 km',
    transmission: 'Diesel',
    carburant: 'Essence',
    prix: 79,
    image: '/assets/images/audi/q7.webp',
  },
  {
    id: 7,
    constructeur: 'Fiat',
    modèle: '500',
    année: 2015,
    consommation: '4,2 L/100 km',
    transmission: 'Manuelle',
    carburant: 'Diesel',
    prix: 29,
    image: '/assets/images/fiat/500.webp',
  },
  {
    id: 8,
    constructeur: 'Fiat',
    modèle: 'Panda',
    année: 2017,
    consommation: '4,5 L/100 km',
    transmission: 'Automatique',
    carburant: 'Essence',
    prix: 29,
    image: '/assets/images/fiat/panda.webp',
  },
  {
    id: 9,
    constructeur: 'Fiat',
    modèle: 'Tipo',
    année: 2019,
    consommation: '4,8 L/100 km',
    transmission: 'Manuelle',
    carburant: 'Diesel',
    prix: 29,
    image: '/assets/images/fiat/tipo.webp',
  },
  {
    id: 10,
    constructeur: 'Fiat',
    modèle: '600',
    année: 2021,
    consommation: '5,2 L/100 km',
    transmission: 'Automatique',
    carburant: 'Essence',
    prix: 49,
    image: '/assets/images/fiat/600.webp',
  },
  {
    id: 11,
    constructeur: 'Fiat',
    modèle: 'Strada',
    année: 2023,
    consommation: '5,5 L/100 km',
    transmission: 'Manuelle',
    carburant: 'Diesel',
    prix: 49,
    image: '/assets/images/fiat/strada.webp',
  },
  {
    id: 12,
    constructeur: 'Fiat',
    modèle: 'Punto',
    année: 2014,
    consommation: '5,8 L/100 km',
    transmission: 'Automatique',
    carburant: 'Essence',
    prix: 49,
    image: '/assets/images/fiat/punto.webp',
  },
  {
    id: 13,
    constructeur: 'BMW',
    modèle: 'Série 1',
    année: 2015,
    consommation: '4,5 L/100 km',
    transmission: 'Manuelle',
    carburant: 'Essence',
    prix: 59,
    image: '/assets/images/bmw/serie1.webp',
  },
  {
    id: 14,
    constructeur: 'BMW',
    modèle: 'Série 3',
    année: 2017,
    consommation: '5,0 L/100 km',
    transmission: 'Automatique',
    carburant: 'Diesel',
    prix: 69,
    image: '/assets/images/bmw/serie3.webp',
  },
  {
    id: 15,
    constructeur: 'BMW',
    modèle: 'X1',
    année: 2019,
    consommation: '5,5 L/100 km',
    transmission: 'Manuelle',
    carburant: 'Essence',
    prix: 79,
    image: '/assets/images/bmw/x1.webp',
  },
  {
    id: 16,
    constructeur: 'BMW',
    modèle: 'X3',
    année: 2020,
    consommation: '6,0 L/100 km',
    transmission: 'Automatique',
    carburant: 'Diesel',
    prix: 89,
    image: '/assets/images/bmw/x3.webp',
  },
  {
    id: 17,
    constructeur: 'BMW',
    modèle: 'Série 5',
    année: 2021,
    consommation: '5,2 L/100 km',
    transmission: 'Manuelle',
    carburant: 'Essence',
    prix: 99,
    image: '/assets/images/bmw/serie5.webp',
  },
  {
    id: 18,
    constructeur: 'BMW',
    modèle: 'X5',
    année: 2023,
    consommation: '6,5 L/100 km',
    transmission: 'Automatique',
    carburant: 'Diesel',
    prix: 109,
    image: '/assets/images/bmw/x5.webp',
  },
  {
    id: 19,
    constructeur: 'Citroën',
    modèle: 'C3',
    année: 2016,
    consommation: '4,2 L/100 km',
    transmission: 'Manuelle',
    carburant: 'Essence',
    prix: 39,
    image: '/assets/images/citroen/c3.webp',
  },
  {
    id: 20,
    constructeur: 'Citroën',
    modèle: 'C4',
    année: 2018,
    consommation: '4,5 L/100 km',
    transmission: 'Automatique',
    carburant: 'Diesel',
    prix: 49,
    image: '/assets/images/citroen/c4.webp',
  },
  {
    id: 21,
    constructeur: 'Citroën',
    modèle: 'C5X',
    année: 2019,
    consommation: '4,8 L/100 km',
    transmission: 'Manuelle',
    carburant: 'Essence',
    prix: 59,
    image: '/assets/images/citroen/c5x.webp',
  },
  {
    id: 22,
    constructeur: 'Citroën',
    modèle: 'DS4',
    année: 2020,
    consommation: '5,0 L/100 km',
    transmission: 'Automatique',
    carburant: 'Diesel',
    prix: 59,
    image: '/assets/images/citroen/ds4.webp',
  },
  {
    id: 23,
    constructeur: 'Citroën',
    modèle: 'Cactus',
    année: 2021,
    consommation: '5,2 L/100 km',
    transmission: 'Manuelle',
    carburant: 'Essence',
    prix: 69,
    image: '/assets/images/citroen/cactus.webp',
  },
  {
    id: 24,
    constructeur: 'Citroën',
    modèle: 'C6',
    année: 2023,
    consommation: '5,5 L/100 km',
    transmission: 'Automatique',
    carburant: 'Diesel',
    prix: 79,
    image: '/assets/images/citroen/c6.webp',
  },
  {
    id: 25,
    constructeur: 'Honda',
    modèle: 'Civic',
    année: 2016,
    consommation: '5,0 L/100 km',
    transmission: 'Manuelle',
    carburant: 'Essence',
    prix: 49,
    image: '/assets/images/honda/civic.webp',
  },
  {
    id: 26,
    constructeur: 'Honda',
    modèle: 'Accord',
    année: 2017,
    consommation: '5,5 L/100 km',
    transmission: 'Automatique',
    carburant: 'Diesel',
    prix: 59,
    image: '/assets/images/honda/accord.webp',
  },
  {
    id: 27,
    constructeur: 'Honda',
    modèle: 'CR-V',
    année: 2018,
    consommation: '6,0 L/100 km',
    transmission: 'Manuelle',
    carburant: 'Essence',
    prix: 69,
    image: '/assets/images/honda/crv.webp',
  },
  {
    id: 28,
    constructeur: 'Honda',
    modèle: 'HR-V',
    année: 2019,
    consommation: '6,2 L/100 km',
    transmission: 'Automatique',
    carburant: 'Diesel',
    prix: 69,
    image: '/assets/images/honda/hrv.webp',
  },
  {
    id: 29,
    constructeur: 'Honda',
    modèle: 'Pilot',
    année: 2020,
    consommation: '6,5 L/100 km',
    transmission: 'Manuelle',
    carburant: 'Essence',
    prix: 79,
    image: '/assets/images/honda/pilot.webp',
  },
  {
    id: 30,
    constructeur: 'Honda',
    modèle: 'Odyssey',
    année: 2021,
    consommation: '7,0 L/100 km',
    transmission: 'Automatique',
    carburant: 'Diesel',
    prix: 89,
    image: '/assets/images/honda/odyssey.webp',
  },
  {
    id: 31,
    constructeur: 'Toyota',
    modèle: 'Corolla',
    année: 2016,
    consommation: '4,8 L/100 km',
    transmission: 'Manuelle',
    carburant: 'Essence',
    prix: 49,
    image: '/assets/images/toyota/corolla.webp',
  },
  {
    id: 32,
    constructeur: 'Toyota',
    modèle: 'Camry',
    année: 2018,
    consommation: '5,2 L/100 km',
    transmission: 'Automatique',
    carburant: 'Diesel',
    prix: 59,
    image: '/assets/images/toyota/camry.webp',
  },
  {
    id: 33,
    constructeur: 'Toyota',
    modèle: 'RAV4',
    année: 2019,
    consommation: '5,5 L/100 km',
    transmission: 'Manuelle',
    carburant: 'Essence',
    prix: 69,
    image: '/assets/images/toyota/rav4.webp',
  },
  {
    id: 34,
    constructeur: 'Toyota',
    modèle: 'Highlander',
    année: 2020,
    consommation: '6,0 L/100 km',
    transmission: 'Automatique',
    carburant: 'Diesel',
    prix: 79,
    image: '/assets/images/toyota/highlander.webp',
  },
  {
    id: 35,
    constructeur: 'Toyota',
    modèle: 'Land Cruiser',
    année: 2021,
    consommation: '6,2 L/100 km',
    transmission: 'Manuelle',
    carburant: 'Essence',
    prix: 89,
    image: '/assets/images/toyota/landcruiser.webp',
  },
  {
    id: 36,
    constructeur: 'Toyota',
    modèle: 'Sienna',
    année: 2023,
    consommation: '6,5 L/100 km',
    transmission: 'Automatique',
    carburant: 'Diesel',
    prix: 99,
    image: '/assets/images/toyota/sienna.webp',
  },
  {
    id: 37,
    constructeur: 'Kia',
    modèle: 'Rio',
    année: 2017,
    consommation: '4,4 L/100 km',
    transmission: 'Manuelle',
    carburant: 'Essence',
    prix: 39,
    image: '/assets/images/kia/rio.webp',
  },
  {
    id: 38,
    constructeur: 'Kia',
    modèle: 'Forte',
    année: 2018,
    consommation: '4,7 L/100 km',
    transmission: 'Automatique',
    carburant: 'Diesel',
    prix: 49,
    image: '/assets/images/kia/forte.webp',
  },
  {
    id: 39,
    constructeur: 'Kia',
    modèle: 'Sportage',
    année: 2019,
    consommation: '5,0 L/100 km',
    transmission: 'Manuelle',
    carburant: 'Essence',
    prix: 59,
    image: '/assets/images/kia/sportage.webp',
  },
  {
    id: 40,
    constructeur: 'Kia',
    modèle: 'Sorento',
    année: 2020,
    consommation: '5,5 L/100 km',
    transmission: 'Automatique',
    carburant: 'Diesel',
    prix: 69,
    image: '/assets/images/kia/sorento.webp',
  },
  {
    id: 41,
    constructeur: 'Kia',
    modèle: 'Niro',
    année: 2021,
    consommation: '5,8 L/100 km',
    transmission: 'Manuelle',
    carburant: 'Essence',
    prix: 69,
    image: '/assets/images/kia/niro.webp',
  },
  {
    id: 42,
    constructeur: 'Kia',
    modèle: 'Telluride',
    année: 2023,
    consommation: '6,2 L/100 km',
    transmission: 'Automatique',
    carburant: 'Diesel',
    prix: 79,
    image: '/assets/images/kia/telluride.webp',
  },
  {
    id: 43,
    constructeur: 'Tesla',
    modèle: 'Model 3',
    année: 2018,
    consommation: '0,0 L/100 km',
    transmission: 'Automatique',
    carburant: 'Electrique',
    prix: 99,
    image: '/assets/images/tesla/model-3.webp',
  },
  {
    id: 44,
    constructeur: 'Tesla',
    modèle: 'Model S',
    année: 2019,
    consommation: '0,0 L/100 km',
    transmission: 'Automatique',
    carburant: 'Electrique',
    prix: 129,
    image: '/assets/images/tesla/model-s.webp',
  },
  {
    id: 45,
    constructeur: 'Tesla',
    modèle: 'Model X',
    année: 2020,
    consommation: '0,0 L/100 km',
    transmission: 'Automatique',
    carburant: 'Electrique',
    prix: 149,
    image: '/assets/images/tesla/model-x.webp',
  },
  {
    id: 46,
    constructeur: 'Tesla',
    modèle: 'Model Y',
    année: 2021,
    consommation: '0,0 L/100 km',
    transmission: 'Automatique',
    carburant: 'Electrique',
    prix: 119,
    image: '/assets/images/tesla/model-y.webp',
  },
  {
    id: 47,
    constructeur: 'Tesla',
    modèle: 'Roadster',
    année: 2022,
    consommation: '0,0 L/100 km',
    transmission: 'Automatique',
    carburant: 'Electrique',
    prix: 179,
    image: '/assets/images/tesla/roadster.webp',
  },
  {
    id: 48,
    constructeur: 'Tesla',
    modèle: 'Cybertruck',
    année: 2023,
    consommation: '0,0 L/100 km',
    transmission: 'Automatique',
    carburant: 'Electrique',
    prix: 199,
    image: '/assets/images/tesla/cybertruck.webp',
  },
  {
    id: 49,
    constructeur: 'Volkswagen',
    modèle: 'Golf',
    année: 2017,
    consommation: '4,5 L/100 km',
    transmission: 'Manuelle',
    carburant: 'Essence',
    prix: 49,
    image: '/assets/images/volkswagen/golf.webp',
  },
  {
    id: 50,
    constructeur: 'Volkswagen',
    modèle: 'Passat',
    année: 2018,
    consommation: '5,0 L/100 km',
    transmission: 'Automatique',
    carburant: 'Diesel',
    prix: 59,
    image: '/assets/images/volkswagen/passat.webp',
  },
  {
    id: 51,
    constructeur: 'Volkswagen',
    modèle: 'Tiguan',
    année: 2019,
    consommation: '5,5 L/100 km',
    transmission: 'Manuelle',
    carburant: 'Essence',
    prix: 69,
    image: '/assets/images/volkswagen/tiguan.webp',
  },
  {
    id: 52,
    constructeur: 'Volkswagen',
    modèle: 'Touareg',
    année: 2020,
    consommation: '6,0 L/100 km',
    transmission: 'Automatique',
    carburant: 'Diesel',
    prix: 79,
    image: '/assets/images/volkswagen/touareg.webp',
  },
  {
    id: 53,
    constructeur: 'Volkswagen',
    modèle: 'Arteon',
    année: 2021,
    consommation: '6,2 L/100 km',
    transmission: 'Manuelle',
    carburant: 'Essence',
    prix: 79,
    image: '/assets/images/volkswagen/arteon.webp',
  },
  {
    id: 54,
    constructeur: 'Volkswagen',
    modèle: 'ID.4',
    année: 2023,
    consommation: '0,0 L/100 km',
    transmission: 'Automatique',
    carburant: 'Electrique',
    prix: 89,
    image: '/assets/images/volkswagen/id4.webp',
  },
  {
    id: 55,
    constructeur: 'Mercedes-Benz',
    modèle: 'A-Class',
    année: 2017,
    consommation: '4,8 L/100 km',
    transmission: 'Manuelle',
    carburant: 'Essence',
    prix: 59,
    image: '/assets/images/mercedes/class-a.webp',
  },
  {
    id: 56,
    constructeur: 'Mercedes-Benz',
    modèle: 'C-Class',
    année: 2018,
    consommation: '5,2 L/100 km',
    transmission: 'Automatique',
    carburant: 'Diesel',
    prix: 69,
    image: '/assets/images/mercedes/class-c.webp',
  },
  {
    id: 57,
    constructeur: 'Mercedes-Benz',
    modèle: 'E-Class',
    année: 2019,
    consommation: '5,5 L/100 km',
    transmission: 'Manuelle',
    carburant: 'Essence',
    prix: 79,
    image: '/assets/images/mercedes/class-e.webp',
  },
  {
    id: 58,
    constructeur: 'Mercedes-Benz',
    modèle: 'GLA',
    année: 2020,
    consommation: '6,0 L/100 km',
    transmission: 'Automatique',
    carburant: 'Diesel',
    prix: 79,
    image: '/assets/images/mercedes/gla.webp',
  },
  {
    id: 59,
    constructeur: 'Mercedes-Benz',
    modèle: 'GLE',
    année: 2021,
    consommation: '6,2 L/100 km',
    transmission: 'Manuelle',
    carburant: 'Essence',
    prix: 89,
    image: '/assets/images/mercedes/gle.webp',
  },
  {
    id: 60,
    constructeur: 'Mercedes-Benz',
    modèle: 'S-Class',
    année: 2023,
    consommation: '6,5 L/100 km',
    transmission: 'Automatique',
    carburant: 'Diesel',
    prix: 99,
    image: '/assets/images/mercedes/class-s.webp',
  },
];
